Selected_Game: Unknown
Load_Order:
  File: 
Mod_Organizer:
  Binary: 
  Install_Path: 
xEdit:
  Binary: 
  Install_Path: 
AutoQAC_Settings:
  Journal_Expiration: 7
  Cleaning_Timeout: 300
  CPU_Threshold: 5
  MO2Mode: false
Skip_Lists: {}
